#include <stdio.h>
#include <string.h>
#include "../src/bigint.h"

/* Test vector generated by scripts/generate_mont_vectors.py
 * If you regenerate vectors, paste the new values here. */

static void print_limbs(const char *label, const bigint512 *x) {
    printf("%s = ", label);
    for (int i = LIMBS - 1; i >= 0; i--) printf("%016lx", x->v[i]);
    printf("\n");
}

static int limbs_equal(const bigint512 *a, const bigint512 *b) {
    for (int i = 0; i < LIMBS; i++) if (a->v[i] != b->v[i]) return 0;
    return 1;
}

int main(void) {
    bigint512 n = {{0xb0c1d2e3f405162dUL, 0x8394a5b6c7d8e9faUL,
                    0x8b1c2d3e4f506172UL, 0x0c3a1b2f4e5d6a79UL,
                    0,0,0,0}};
    bigint512 a = {{0xa00010427000020cUL, 0x831024164090a9c8UL,
                    0x8b10241648102140UL, 0x0012100648102a49UL,
                    0,0,0,0}};
    bigint512 b = {{0x20c0d0a200050400UL, 0x019484b201806142UL,
                    0x011c0c3a09006142UL, 0x003a182a08056041UL,
                    0,0,0,0}};
    bigint512 expected = {{0x6c8a80bbd808de9bUL, 0x359d7967ece1deacUL,
                           0xbb551143ff16ee11UL, 0x022de974b90a0b52UL,
                           0,0,0,0}};
    uint64_t n_inv = 0xf79e4ea82476565bUL;

    bigint512 result;
    bigint_mont_mul(&result, &a, &b, &n, n_inv);

    print_limbs("got     ", &result);
    print_limbs("expected", &expected);

    if (limbs_equal(&result, &expected)) {
        printf("PASS: Montgomery multiplication matches reference\n");
        return 0;
    } else {
        printf("FAIL: Montgomery multiplication does NOT match reference\n");
        printf("This must be fixed before proceeding to exponentiation.\n");
        return 1;
    }
}
